import fs from "fs/promises";

// Comprehensive list of real Portuguese verbs with translations
const verbTranslations = {
  // Common -ar verbs (regular)
  falar: "to speak/talk",
  trabalhar: "to work",
  estudar: "to study",
  morar: "to live/reside",
  gostar: "to like",
  precisar: "to need",
  pensar: "to think",
  andar: "to walk",
  chegar: "to arrive",
  começar: "to begin/start",
  parar: "to stop",
  passar: "to pass",
  levar: "to take/carry",
  deixar: "to leave/let",
  encontrar: "to find/meet",
  esperar: "to wait/hope",
  olhar: "to look",
  perguntar: "to ask",
  responder: "to answer",
  explicar: "to explain",
  mostrar: "to show",
  ajudar: "to help",
  chamar: "to call",
  procurar: "to search/look for",
  entrar: "to enter",
  voltar: "to return",
  jogar: "to play",
  dançar: "to dance",
  viajar: "to travel",
  comprar: "to buy",
  usar: "to use",
  tocar: "to touch/play",
  brincar: "to play",
  amar: "to love",
  odiar: "to hate",
  acordar: "to wake up",
  sonhar: "to dream",
  cantar: "to sing",
  nadar: "to swim",
  lavar: "to wash",
  arrumar: "to arrange",
  casar: "to marry",
  plantar: "to plant",
  pescar: "to fish",
  pular: "to jump",
  voar: "to fly",
  gastar: "to spend",
  ligar: "to call/turn on",
  apagar: "to turn off",
  acender: "to turn on",
  fechar: "to close",
  abrir: "to open",
  mandar: "to send",
  enviar: "to send",
  receber: "to receive",
  aceitar: "to accept",
  rejeitar: "to reject",
  admirar: "to admire",
  adotar: "to adopt",
  almoçar: "to have lunch",
  alugar: "to rent",
  apresentar: "to present",
  aproveitar: "to take advantage",
  atacar: "to attack",
  atender: "to attend",
  atrasar: "to delay",
  aumentar: "to increase",
  avisar: "to warn",
  baixar: "to download/lower",
  bater: "to hit/beat",
  beijar: "to kiss",
  brigar: "to fight",
  buscar: "to search",
  calar: "to silence",
  caminhar: "to walk",
  cancelar: "to cancel",
  cansar: "to tire",
  carregar: "to load/carry",
  caçar: "to hunt",
  celebrar: "to celebrate",
  chutar: "to kick",
  colaborar: "to collaborate",
  colocar: "to put/place",
  combinar: "to combine",
  comemorar: "to celebrate",
  comparar: "to compare",
  compartilhar: "to share",
  completar: "to complete",
  concordar: "to agree",
  conquistar: "to conquer",
  consertar: "to fix",
  consultar: "to consult",
  contar: "to count/tell",
  continuar: "to continue",
  convidar: "to invite",
  cooperar: "to cooperate",
  cortar: "to cut",
  costurar: "to sew",
  criar: "to create",
  cruzar: "to cross",
  cuidar: "to take care",
  curar: "to cure",
  deitar: "to lie down",
  demorar: "to take time",
  descer: "to go down",
  desenhar: "to draw",
  desistir: "to give up",
  desligar: "to turn off",
  despachar: "to dispatch",
  despedir: "to fire",
  destruir: "to destroy",
  detestar: "to detest",
  dirigir: "to drive",
  discutir: "to discuss",
  dividir: "to divide",
  doar: "to donate",
  dobrar: "to fold",
  dominar: "to dominate",
  duvidar: "to doubt",
  educar: "to educate",
  eliminar: "to eliminate",
  elogiar: "to praise",
  embarcar: "to board",
  empatar: "to tie",
  empregar: "to employ",
  empurrar: "to push",
  enfeitar: "to decorate",
  enfrentar: "to face",
  enganar: "to deceive",
  engolir: "to swallow",
  ensinar: "to teach",
  errar: "to make mistakes",
  escapar: "to escape",
  escolher: "to choose",
  escutar: "to listen",
  esquecer: "to forget",
  estacionar: "to park",
  evitar: "to avoid",
  examinar: "to examine",
  exigir: "to demand",
  existir: "to exist",
  explorar: "to explore",
  fabricar: "to manufacture",
  faltar: "to lack",
  felicitar: "to congratulate",
  ferir: "to hurt",
  festejar: "to celebrate",
  filmar: "to film",
  fingir: "to pretend",
  fitar: "to stare",
  focar: "to focus",
  forçar: "to force",
  formar: "to form",
  fotografar: "to photograph",
  frear: "to brake",
  fritar: "to fry",
  ganhar: "to win/earn",
  girar: "to rotate",
  gozar: "to enjoy",
  gravar: "to record",
  gritar: "to shout",
  guardar: "to keep",
  guiar: "to guide",
  guerrear: "to wage war",
  habitar: "to inhabit",
  herdar: "to inherit",
  homenagear: "to honor",
  hospedar: "to host",
  iluminar: "to illuminate",
  imaginar: "to imagine",
  imitar: "to imitate",
  impedir: "to prevent",
  importar: "to import",
  imprimir: "to print",
  inaugurar: "to inaugurate",
  incomodar: "to bother",
  indicar: "to indicate",
  informar: "to inform",
  iniciar: "to initiate",
  insistir: "to insist",
  inspirar: "to inspire",
  instalar: "to install",
  insultar: "to insult",
  interessar: "to interest",
  interromper: "to interrupt",
  introduzir: "to introduce",
  invadir: "to invade",
  inventar: "to invent",
  investigar: "to investigate",
  jantar: "to have dinner",
  juntar: "to join",
  justificar: "to justify",
  ladrar: "to bark",
  lamentar: "to lament",
  lançar: "to launch",
  limpar: "to clean",
  listar: "to list",
  localizar: "to locate",
  louvar: "to praise",
  lutar: "to fight",
  machucar: "to hurt",
  manter: "to maintain",
  marcar: "to mark",
  matar: "to kill",
  medir: "to measure",
  melhorar: "to improve",
  mentir: "to lie",
  mergulhar: "to dive",
  mexer: "to move",
  mirar: "to aim",
  misturar: "to mix",
  mudar: "to change",
  multiplicar: "to multiply",
  narrar: "to narrate",
  necessitar: "to need",
  negar: "to deny",
  negociar: "to negotiate",
  nomear: "to name",
  notar: "to notice",
  obedecer: "to obey",
  observar: "to observe",
  ocupar: "to occupy",
  oferecer: "to offer",
  operar: "to operate",
  opinar: "to opine",
  ordenar: "to order",
  organizar: "to organize",
  orientar: "to guide",
  ouvir: "to hear",
  pagar: "to pay",
  participar: "to participate",
  passear: "to walk",
  pedalar: "to pedal",
  pegar: "to take/grab",
  perceber: "to perceive",
  perder: "to lose",
  perdoar: "to forgive",
  permitir: "to permit",
  persuadir: "to persuade",
  pesar: "to weigh",
  pesquisar: "to research",
  pintar: "to paint",
  pisar: "to step",
  planejar: "to plan",
  pousar: "to land",
  praticar: "to practice",
  preparar: "to prepare",
  preservar: "to preserve",
  prestar: "to lend",
  produzir: "to produce",
  proteger: "to protect",
  provar: "to prove/taste",
  publicar: "to publish",
  punir: "to punish",
  quebrar: "to break",
  queimar: "to burn",
  queixar: "to complain",
  questionar: "to question",
  quitar: "to pay off",
  ralar: "to grate",
  realizar: "to realize",
  reclamar: "to complain",
  recolher: "to collect",
  recomendar: "to recommend",
  reconhecer: "to recognize",
  recordar: "to remember",
  recuperar: "to recover",
  recusar: "to refuse",
  reduzir: "to reduce",
  reembolsar: "to reimburse",
  reencaminhar: "to forward",
  reencontrar: "to meet again",
  refletir: "to reflect",
  reformar: "to reform",
  refrigerar: "to refrigerate",
  regatar: "to rescue",
  registrar: "to register",
  regular: "to regulate",
  relatar: "to report",
  relaxar: "to relax",
  relevar: "to reveal",
  remar: "to row",
  remover: "to remove",
  renovar: "to renew",
  reparar: "to repair",
  repetir: "to repeat",
  resgatar: "to rescue",
  residir: "to reside",
  resistir: "to resist",
  resolver: "to solve",
  respeitar: "to respect",
  respirar: "to breathe",
  restaurar: "to restore",
  resultar: "to result",
  retirar: "to withdraw",
  reunir: "to gather",
  reutilizar: "to reuse",
  revelar: "to reveal",
  rever: "to review",
  revidar: "to retaliate",
  rezar: "to pray",
  rir: "to laugh",
  rodar: "to roll",
  roer: "to gnaw",
  romper: "to break",
  roubar: "to steal",
  saber: "to know",
  sair: "to go out",
  salvar: "to save",
  sambar: "to samba",
  sangrar: "to bleed",
  sarar: "to heal",
  satisfazer: "to satisfy",
  saudar: "to greet",
  secar: "to dry",
  seguir: "to follow",
  sentar: "to sit",
  sentir: "to feel",
  separar: "to separate",
  servir: "to serve",
  significar: "to mean",
  simbolizar: "to symbolize",
  simplificar: "to simplify",
  sinalizar: "to signal",
  situar: "to situate",
  soar: "to sound",
  sobreviver: "to survive",
  socorrer: "to help",
  sofrer: "to suffer",
  solicitar: "to request",
  soltar: "to release",
  somar: "to add",
  sonhar: "to dream",
  sorrir: "to smile",
  sortear: "to draw",
  subir: "to go up",
  sugerir: "to suggest",
  sumir: "to disappear",
  superar: "to overcome",
  suportar: "to support",
  surgir: "to arise",
  surpreender: "to surprise",
  suspender: "to suspend",
  tentar: "to try",
  terminar: "to finish",
  tocar: "to touch/play",
  tomar: "to take",
  tossir: "to cough",
  trair: "to betray",
  trancar: "to lock",
  transformar: "to transform",
  transmitir: "to transmit",
  transportar: "to transport",
  tratar: "to treat",
  treinar: "to train",
  trocar: "to exchange",
  unir: "to unite",
  usar: "to use",
  vacinar: "to vaccinate",
  valer: "to be worth",
  variar: "to vary",
  vender: "to sell",
  vibrar: "to vibrate",
  visitar: "to visit",
  votar: "to vote",
  zangar: "to anger",

  // Common -er verbs (regular)
  comer: "to eat",
  beber: "to drink",
  vender: "to sell",
  aprender: "to learn",
  correr: "to run",
  escrever: "to write",
  ler: "to read",
  receber: "to receive",
  viver: "to live",
  temer: "to fear",
  escolher: "to choose",
  perder: "to lose",
  responder: "to answer",
  romper: "to break",
  sofrer: "to suffer",
  vencer: "to win",
  proteger: "to protect",
  esquecer: "to forget",
  chover: "to rain",
  caber: "to fit",
  crer: "to believe",
  trazer: "to bring",
  vir: "to come",

  // Common -ir verbs (regular)
  partir: "to leave",
  abrir: "to open",
  assistir: "to watch/attend",
  decidir: "to decide",
  descobrir: "to discover",
  dividir: "to divide",
  dormir: "to sleep",
  existir: "to exist",
  fugir: "to flee",
  insistir: "to insist",
  mentir: "to lie",
  ouvir: "to hear",
  pedir: "to ask/request",
  permitir: "to permit",
  preferir: "to prefer",
  proibir: "to prohibit",
  repetir: "to repeat",
  seguir: "to follow",
  sentir: "to feel",
  servir: "to serve",
  sorrir: "to smile",
  subir: "to go up",
  sumir: "to disappear",
  surgir: "to arise",
  vestir: "to dress",
  agir: "to act",
  admitir: "to admit",
  aplaudir: "to applaud",
  conduzir: "to drive",
  construir: "to build",
  contribuir: "to contribute",
  cumprir: "to fulfill",
  discutir: "to discuss",
  distrair: "to distract",
  divertir: "to entertain",
  emitir: "to emit",
  expandir: "to expand",
  ferir: "to hurt",
  garantir: "to guarantee",
  imprimir: "to print",
  incluir: "to include",
  instruir: "to instruct",
  invadir: "to invade",
  medir: "to measure",
  omitir: "to omit",
  progredir: "to progress",
  prover: "to provide",
  reagir: "to react",
  resistir: "to resist",
  reunir: "to gather",
  sortir: "to sort",
  traduzir: "to translate",
  transmitir: "to transmit",
  unir: "to unite",

  // Irregular verbs (most common)
  ser: "to be",
  estar: "to be (temporary)",
  ter: "to have",
  ir: "to go",
  fazer: "to do/make",
  dizer: "to say",
  ver: "to see",
  dar: "to give",
  saber: "to know",
  querer: "to want",
  poder: "to be able to",
  trazer: "to bring",
  vir: "to come",
  pôr: "to put",
  haver: "to exist",
};

// Comprehensive list of real Portuguese verbs
const realPortugueseVerbs = [
  // Common -ar verbs (regular)
  "falar",
  "trabalhar",
  "estudar",
  "morar",
  "gostar",
  "precisar",
  "pensar",
  "andar",
  "chegar",
  "começar",
  "parar",
  "passar",
  "levar",
  "deixar",
  "encontrar",
  "esperar",
  "olhar",
  "perguntar",
  "responder",
  "explicar",
  "mostrar",
  "ajudar",
  "chamar",
  "procurar",
  "entrar",
  "voltar",
  "jogar",
  "dançar",
  "viajar",
  "comprar",
  "usar",
  "tocar",
  "brincar",
  "amar",
  "odiar",
  "acordar",
  "sonhar",
  "cantar",
  "nadar",
  "lavar",
  "arrumar",
  "casar",
  "plantar",
  "pescar",
  "pular",
  "voar",
  "gastar",
  "ligar",
  "apagar",
  "acender",
  "fechar",
  "abrir",
  "mandar",
  "enviar",
  "receber",
  "aceitar",
  "rejeitar",
  "admirar",
  "adotar",
  "almoçar",
  "alugar",
  "apresentar",
  "aproveitar",
  "atacar",
  "atender",
  "atrasar",
  "aumentar",
  "avisar",
  "baixar",
  "bater",
  "beijar",
  "brigar",
  "buscar",
  "calar",
  "caminhar",
  "cancelar",
  "cansar",
  "carregar",
  "caçar",
  "celebrar",
  "chutar",
  "colaborar",
  "colocar",
  "combinar",
  "comemorar",
  "comparar",
  "compartilhar",
  "completar",
  "concordar",
  "conquistar",
  "consertar",
  "consultar",
  "contar",
  "continuar",
  "convidar",
  "cooperar",
  "cortar",
  "costurar",
  "criar",
  "cruzar",
  "cuidar",
  "curar",
  "deitar",
  "demorar",
  "descer",
  "desenhar",
  "desistir",
  "desligar",
  "despachar",
  "despedir",
  "destruir",
  "detestar",
  "dirigir",
  "discutir",
  "dividir",
  "doar",
  "dobrar",
  "dominar",
  "duvidar",
  "educar",
  "eliminar",
  "elogiar",
  "embarcar",
  "empatar",
  "empregar",
  "empurrar",
  "enfeitar",
  "enfrentar",
  "enganar",
  "engolir",
  "ensinar",
  "errar",
  "escapar",
  "escolher",
  "escutar",
  "esquecer",
  "estacionar",
  "evitar",
  "examinar",
  "exigir",
  "existir",
  "explorar",
  "fabricar",
  "faltar",
  "felicitar",
  "ferir",
  "festejar",
  "filmar",
  "fingir",
  "fitar",
  "focar",
  "forçar",
  "formar",
  "fotografar",
  "frear",
  "fritar",
  "ganhar",
  "girar",
  "gozar",
  "gravar",
  "gritar",
  "guardar",
  "guiar",
  "guerrear",
  "habitar",
  "herdar",
  "homenagear",
  "hospedar",
  "iluminar",
  "imaginar",
  "imitar",
  "impedir",
  "importar",
  "imprimir",
  "inaugurar",
  "incomodar",
  "indicar",
  "informar",
  "iniciar",
  "insistir",
  "inspirar",
  "instalar",
  "insultar",
  "interessar",
  "interromper",
  "introduzir",
  "invadir",
  "inventar",
  "investigar",
  "jantar",
  "juntar",
  "justificar",
  "ladrar",
  "lamentar",
  "lançar",
  "limpar",
  "listar",
  "localizar",
  "louvar",
  "lutar",
  "machucar",
  "manter",
  "marcar",
  "matar",
  "medir",
  "melhorar",
  "mentir",
  "mergulhar",
  "mexer",
  "mirar",
  "misturar",
  "mudar",
  "multiplicar",
  "narrar",
  "necessitar",
  "negar",
  "negociar",
  "nomear",
  "notar",
  "obedecer",
  "observar",
  "ocupar",
  "oferecer",
  "operar",
  "opinar",
  "ordenar",
  "organizar",
  "orientar",
  "ouvir",
  "pagar",
  "participar",
  "passear",
  "pedalar",
  "pegar",
  "perceber",
  "perder",
  "perdoar",
  "permitir",
  "persuadir",
  "pesar",
  "pesquisar",
  "pintar",
  "pisar",
  "planejar",
  "pousar",
  "praticar",
  "preparar",
  "preservar",
  "prestar",
  "produzir",
  "proteger",
  "provar",
  "publicar",
  "punir",
  "quebrar",
  "queimar",
  "queixar",
  "questionar",
  "quitar",
  "ralar",
  "realizar",
  "reclamar",
  "recolher",
  "recomendar",
  "reconhecer",
  "recordar",
  "recuperar",
  "recusar",
  "reduzir",
  "reembolsar",
  "reencaminhar",
  "reencontrar",
  "refletir",
  "reformar",
  "refrigerar",
  "regatar",
  "registrar",
  "regular",
  "relatar",
  "relaxar",
  "relevar",
  "remar",
  "remover",
  "renovar",
  "reparar",
  "repetir",
  "resgatar",
  "residir",
  "resistir",
  "resolver",
  "respeitar",
  "respirar",
  "restaurar",
  "resultar",
  "retirar",
  "reunir",
  "reutilizar",
  "revelar",
  "rever",
  "revidar",
  "rezar",
  "rir",
  "rodar",
  "roer",
  "romper",
  "roubar",
  "saber",
  "sair",
  "salvar",
  "sambar",
  "sangrar",
  "sarar",
  "satisfazer",
  "saudar",
  "secar",
  "seguir",
  "sentar",
  "sentir",
  "separar",
  "servir",
  "significar",
  "simbolizar",
  "simplificar",
  "sinalizar",
  "situar",
  "soar",
  "sobreviver",
  "socorrer",
  "sofrer",
  "solicitar",
  "soltar",
  "somar",
  "sonhar",
  "sorrir",
  "sortear",
  "subir",
  "sugerir",
  "sumir",
  "superar",
  "suportar",
  "surgir",
  "surpreender",
  "suspender",
  "tentar",
  "terminar",
  "tocar",
  "tomar",
  "tossir",
  "trair",
  "trancar",
  "transformar",
  "transmitir",
  "transportar",
  "tratar",
  "treinar",
  "trocar",
  "unir",
  "usar",
  "vacinar",
  "valer",
  "variar",
  "vender",
  "viajar",
  "vibrar",
  "visitar",
  "voar",
  "voltar",
  "votar",
  "zangar",

  // Common -er verbs (regular)
  "comer",
  "beber",
  "vender",
  "aprender",
  "correr",
  "escrever",
  "ler",
  "receber",
  "viver",
  "temer",
  "escolher",
  "perder",
  "responder",
  "romper",
  "sofrer",
  "vencer",
  "proteger",
  "esquecer",
  "chover",
  "caber",
  "crer",
  "trazer",
  "vir",

  // Common -ir verbs (regular)
  "partir",
  "abrir",
  "assistir",
  "decidir",
  "descobrir",
  "dividir",
  "dormir",
  "existir",
  "fugir",
  "insistir",
  "mentir",
  "ouvir",
  "pedir",
  "permitir",
  "preferir",
  "proibir",
  "repetir",
  "seguir",
  "sentir",
  "servir",
  "sorrir",
  "subir",
  "sumir",
  "surgir",
  "vestir",
  "agir",
  "admitir",
  "aplaudir",
  "conduzir",
  "construir",
  "contribuir",
  "cumprir",
  "discutir",
  "distrair",
  "divertir",
  "emitir",
  "expandir",
  "ferir",
  "garantir",
  "imprimir",
  "incluir",
  "instruir",
  "invadir",
  "medir",
  "omitir",
  "progredir",
  "prover",
  "reagir",
  "resistir",
  "reunir",
  "sortir",
  "traduzir",
  "transmitir",
  "unir",

  // Irregular verbs (most common)
  "ser",
  "estar",
  "ter",
  "ir",
  "fazer",
  "dizer",
  "ver",
  "dar",
  "saber",
  "querer",
  "poder",
  "trazer",
  "vir",
  "pôr",
  "haver",
  "ficar",
  "chegar",
  "passar",
  "deixar",
  "falar",
  "trabalhar",
  "estudar",
  "morar",
  "gostar",
  "precisar",
  "pensar",
  "andar",
  "começar",
  "parar",
  "levar",
  "encontrar",
  "esperar",
  "olhar",
  "perguntar",
  "responder",
  "explicar",
  "mostrar",
  "ajudar",
  "chamar",
  "procurar",
  "entrar",
  "voltar",
  "jogar",
  "dançar",
  "viajar",
  "comprar",
  "usar",
  "tocar",
  "brincar",
  "amar",
  "odiar",
  "acordar",
  "sonhar",
  "cantar",
  "nadar",
  "lavar",
  "arrumar",
  "casar",
  "plantar",
  "pescar",
  "pular",
  "voar",
  "gastar",
  "ligar",
  "apagar",
  "acender",
  "fechar",
  "abrir",
  "mandar",
  "enviar",
  "aceitar",
  "rejeitar",
  "admirar",
  "adotar",
  "almoçar",
  "alugar",
  "apresentar",
  "aproveitar",
  "atacar",
  "atender",
  "atrasar",
  "aumentar",
  "avisar",
  "baixar",
  "bater",
  "beijar",
  "brigar",
  "buscar",
  "calar",
  "caminhar",
  "cancelar",
  "cansar",
  "carregar",
  "caçar",
  "celebrar",
  "chutar",
  "colaborar",
  "colocar",
  "combinar",
  "comemorar",
  "comparar",
  "compartilhar",
  "completar",
  "concordar",
  "conquistar",
  "consertar",
  "consultar",
  "contar",
  "continuar",
  "convidar",
  "cooperar",
  "cortar",
  "costurar",
  "criar",
  "cruzar",
  "cuidar",
  "curar",
  "deitar",
  "demorar",
  "descer",
  "desenhar",
  "desistir",
  "desligar",
  "despachar",
  "despedir",
  "destruir",
  "detestar",
  "dirigir",
  "discutir",
  "dividir",
  "doar",
  "dobrar",
  "dominar",
  "duvidar",
  "educar",
  "eliminar",
  "elogiar",
  "embarcar",
  "empatar",
  "empregar",
  "empurrar",
  "enfeitar",
  "enfrentar",
  "enganar",
  "engolir",
  "ensinar",
  "errar",
  "escapar",
  "escolher",
  "escutar",
  "esquecer",
  "estacionar",
  "evitar",
  "examinar",
  "exigir",
  "existir",
  "explorar",
  "fabricar",
  "faltar",
  "felicitar",
  "ferir",
  "festejar",
  "filmar",
  "fingir",
  "fitar",
  "focar",
  "forçar",
  "formar",
  "fotografar",
  "frear",
  "fritar",
  "ganhar",
  "girar",
  "gozar",
  "gravar",
  "gritar",
  "guardar",
  "guiar",
  "guerrear",
  "habitar",
  "herdar",
  "homenagear",
  "hospedar",
  "iluminar",
  "imaginar",
  "imitar",
  "impedir",
  "importar",
  "imprimir",
  "inaugurar",
  "incomodar",
  "indicar",
  "informar",
  "iniciar",
  "insistir",
  "inspirar",
  "instalar",
  "insultar",
  "interessar",
  "interromper",
  "introduzir",
  "invadir",
  "inventar",
  "investigar",
  "jantar",
  "juntar",
  "justificar",
  "ladrar",
  "lamentar",
  "lançar",
  "limpar",
  "listar",
  "localizar",
  "louvar",
  "lutar",
  "machucar",
  "manter",
  "marcar",
  "matar",
  "medir",
  "melhorar",
  "mentir",
  "mergulhar",
  "mexer",
  "mirar",
  "misturar",
  "mudar",
  "multiplicar",
  "narrar",
  "necessitar",
  "negar",
  "negociar",
  "nomear",
  "notar",
  "obedecer",
  "observar",
  "ocupar",
  "oferecer",
  "operar",
  "opinar",
  "ordenar",
  "organizar",
  "orientar",
  "ouvir",
  "pagar",
  "participar",
  "passear",
  "pedalar",
  "pegar",
  "perceber",
  "perder",
  "perdoar",
  "permitir",
  "persuadir",
  "pesar",
  "pesquisar",
  "pintar",
  "pisar",
  "planejar",
  "pousar",
  "praticar",
  "preparar",
  "preservar",
  "prestar",
  "produzir",
  "proteger",
  "provar",
  "publicar",
  "punir",
  "quebrar",
  "queimar",
  "queixar",
  "questionar",
  "quitar",
  "ralar",
  "realizar",
  "reclamar",
  "recolher",
  "recomendar",
  "reconhecer",
  "recordar",
  "recuperar",
  "recusar",
  "reduzir",
  "reembolsar",
  "reencaminhar",
  "reencontrar",
  "refletir",
  "reformar",
  "refrigerar",
  "regatar",
  "registrar",
  "regular",
  "relatar",
  "relaxar",
  "relevar",
  "remar",
  "remover",
  "renovar",
  "reparar",
  "repetir",
  "resgatar",
  "residir",
  "resistir",
  "resolver",
  "respeitar",
  "respirar",
  "restaurar",
  "resultar",
  "retirar",
  "reunir",
  "reutilizar",
  "revelar",
  "rever",
  "revidar",
  "rezar",
  "rir",
  "rodar",
  "roer",
  "romper",
  "roubar",
  "saber",
  "sair",
  "salvar",
  "sambar",
  "sangrar",
  "sarar",
  "satisfazer",
  "saudar",
  "secar",
  "seguir",
  "sentar",
  "sentir",
  "separar",
  "servir",
  "significar",
  "simbolizar",
  "simplificar",
  "sinalizar",
  "situar",
  "soar",
  "sobreviver",
  "socorrer",
  "sofrer",
  "solicitar",
  "soltar",
  "somar",
  "sonhar",
  "sorrir",
  "sortear",
  "subir",
  "sugerir",
  "sumir",
  "superar",
  "suportar",
  "surgir",
  "surpreender",
  "suspender",
  "tentar",
  "terminar",
  "tocar",
  "tomar",
  "tossir",
  "trair",
  "trancar",
  "transformar",
  "transmitir",
  "transportar",
  "tratar",
  "treinar",
  "trocar",
  "unir",
  "usar",
  "vacinar",
  "valer",
  "variar",
  "vender",
  "viajar",
  "vibrar",
  "visitar",
  "voar",
  "voltar",
  "votar",
  "zangar",
];

// Remove duplicates and ensure we have unique verbs
const allUniqueVerbs = [
  ...new Set(realPortugueseVerbs),
];

// Define the most important irregular verbs to always include
const importantIrregularVerbs = [
  "ser",
  "estar",
  "ter",
  "ir",
  "fazer",
  "dizer",
  "ver",
  "dar",
  "saber",
  "querer",
  "poder",
  "trazer",
  "vir",
  "pôr",
  "haver",
];

// Get regular verbs (excluding irregular ones)
const regularVerbs =
  allUniqueVerbs.filter(
    (verb) =>
      !importantIrregularVerbs.includes(
        verb,
      ),
  );

// Take the first 285 regular verbs plus the 15 irregular verbs = 300 total
const uniqueVerbs = [
  ...regularVerbs.slice(0, 285),
  ...importantIrregularVerbs,
];

function regularConjugations(
  inf,
  type,
) {
  const stem = inf.slice(0, -2);
  let endings = {};
  if (type === "ar") {
    endings = {
      presentIndicative: [
        "o",
        "as",
        "a",
        "amos",
        "am",
      ],
      preteriteIndicative: [
        "ei",
        "aste",
        "ou",
        "amos",
        "aram",
      ],
      imperfectIndicative: [
        "ava",
        "avas",
        "ava",
        "ávamos",
        "avam",
      ],
      futureIndicative: [
        "arei",
        "arás",
        "ará",
        "aremos",
        "arão",
      ],
      conditionalIndicative: [
        "aria",
        "arias",
        "aria",
        "aríamos",
        "ariam",
      ],
      presentSubjunctive: [
        "e",
        "es",
        "e",
        "emos",
        "em",
      ],
      imperfectSubjunctive: [
        "asse",
        "asses",
        "asse",
        "ássemos",
        "assem",
      ],
      imperative: [
        null,
        "a",
        "e",
        "emos",
        "em",
      ],
    };
  } else if (type === "er") {
    endings = {
      presentIndicative: [
        "o",
        "es",
        "e",
        "emos",
        "em",
      ],
      preteriteIndicative: [
        "i",
        "este",
        "eu",
        "emos",
        "eram",
      ],
      imperfectIndicative: [
        "ia",
        "ias",
        "ia",
        "íamos",
        "iam",
      ],
      futureIndicative: [
        "erei",
        "erás",
        "erá",
        "eremos",
        "erão",
      ],
      conditionalIndicative: [
        "eria",
        "erias",
        "eria",
        "eríamos",
        "eriam",
      ],
      presentSubjunctive: [
        "a",
        "as",
        "a",
        "amos",
        "am",
      ],
      imperfectSubjunctive: [
        "esse",
        "esses",
        "esse",
        "êssemos",
        "essem",
      ],
      imperative: [
        null,
        "e",
        "a",
        "amos",
        "am",
      ],
    };
  } else if (type === "ir") {
    endings = {
      presentIndicative: [
        "o",
        "es",
        "e",
        "imos",
        "em",
      ],
      preteriteIndicative: [
        "i",
        "iste",
        "iu",
        "imos",
        "iram",
      ],
      imperfectIndicative: [
        "ia",
        "ias",
        "ia",
        "íamos",
        "iam",
      ],
      futureIndicative: [
        "irei",
        "irás",
        "irá",
        "iremos",
        "irão",
      ],
      conditionalIndicative: [
        "iria",
        "irias",
        "iria",
        "iríamos",
        "iriam",
      ],
      presentSubjunctive: [
        "a",
        "as",
        "a",
        "amos",
        "am",
      ],
      imperfectSubjunctive: [
        "isse",
        "isses",
        "isse",
        "íssemos",
        "issem",
      ],
      imperative: [
        null,
        "e",
        "a",
        "amos",
        "am",
      ],
    };
  }
  const pronouns = [
    "eu",
    "tu",
    "voce",
    "nos",
    "voces",
  ];
  const tenses = Object.keys(endings);
  const conjugations = {};
  for (const tense of tenses) {
    conjugations[tense] = {};
    endings[tense].forEach(
      (ending, i) => {
        if (ending !== null) {
          conjugations[tense][
            pronouns[i]
          ] = stem + ending;
        }
      },
    );
  }
  return conjugations;
}

async function main() {
  const allVerbs = [];

  // Add all real Portuguese verbs
  uniqueVerbs.forEach((verb) => {
    const verbType = verb.endsWith("ar")
      ? "ar"
      : verb.endsWith("er")
      ? "er"
      : "ir";
    const regularity = [
      "ser",
      "estar",
      "ter",
      "ir",
      "fazer",
      "dizer",
      "ver",
      "dar",
      "saber",
      "querer",
      "poder",
      "trazer",
      "vir",
      "pôr",
      "haver",
    ].includes(verb)
      ? "irregular"
      : "regular";
    const translation =
      verbTranslations[verb] || "";

    allVerbs.push({
      verb,
      infinitive: verb,
      translation,
      regularity,
      conjugations:
        regularity === "regular"
          ? regularConjugations(
              verb,
              verbType,
            )
          : {},
    });
  });

  console.log(
    `Generated ${allVerbs.length} unique Portuguese verbs`,
  );
  console.log(
    `Regular verbs: ${
      allVerbs.filter(
        (v) =>
          v.regularity === "regular",
      ).length
    }`,
  );
  console.log(
    `Irregular verbs: ${
      allVerbs.filter(
        (v) =>
          v.regularity === "irregular",
      ).length
    }`,
  );

  await fs.writeFile(
    "src/data/verbs.json",
    JSON.stringify(allVerbs, null, 2),
  );
  console.log(
    "Generated src/data/verbs.json with",
    allVerbs.length,
    "verbs!",
  );
}

main();
